name: pestpp_tester
channels:
  - conda-forge
dependencies:
  # required
  - python=3.9
  - numpy>=1.15.0
  - pandas
  - scipy
  # optional
  - matplotlib>=1.4.0
  - pyshp
  - jinja2
  # tests
  - coveralls
  - nose-timer
  - pytest-xdist
  - nbmake
  - shapely
  - flopy
  - mfpymake
  - imp
  - nose
